/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 9.10 and DSP System Toolbox 9.12.
 * Generated on: 03-Aug-2026 10:15:17
 */

/*
 * 离散时间 FIR 滤波器(实数)
 * ----------------
 * 滤波器结构    : 直接型 FIR
 * 滤波器长度    : 48
 * 稳定       : 是
 * 线性相位     : 是 (Type 2)
 * 算术       : fixed
 * 分子       : s16,18 -> [-1.250000e-01 1.250000e-01)
 * 输入       : s16,15 -> [-1 1)
 * 滤波器内部选项  : Full Precision
 *   输出     : s35,33 -> [-2 2)  (auto determined)
 *   乘积     : s31,33 -> [-1.250000e-01 1.250000e-01)  (auto determined)
 *   累加器    : s35,33 -> [-2 2)  (auto determined)
 *   取整模式   : No rounding
 *   溢出模式   : No overflow
 */

/* General type conversion for MATLAB generated C-code  */
#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * C:\Program Files\Polyspace\R2021a\extern\include\tmwtypes.h 
 */
/*
 * Warning - Filter coefficients were truncated to fit specified data type.  
 *   The resulting response may not match generated theoretical response.
 *   Use the Filter Design & Analysis Tool to design accurate
 *   int16 filter coefficients.
 */
const int BL = 48;
const int16_T B[48] = {
        8,    196,    207,    275,    310,    292,    202,     30,   -216,
     -514,   -818,  -1072,  -1204,  -1148,   -846,   -265,    597,   1705,
     2984,   4332,   5626,   6739,   7554,   7985,   7985,   7554,   6739,
     5626,   4332,   2984,   1705,    597,   -265,   -846,  -1148,  -1204,
    -1072,   -818,   -514,   -216,     30,    202,    292,    310,    275,
      207,    196,      8
};
